# NUMPY

Creating Array

In [1]:
import numpy as np

a = np.array([1, 2, 3])

In [2]:
a

array([1, 2, 3])

In [3]:
# you can easily creat an array filled with 0s:

np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [4]:
# or an array filled with 1s:

np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# you can create an array with a range of elements

    Add, Remove, Sort

In [5]:
arr = np.array ([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.append(arr, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 1])

In [7]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [8]:
arr = np.array ([2, 1, 5, 3, 7, 4, 6, 8])

In [9]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

# shape and size

ndarray.ndim()
ndarray.size()
ndarray.

In [ ]:
array_example = np.array ([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3]]])

In [10]:
array_example.ndim

NameError: name 'array_example' is not defined

In [ ]:
array_example.size

In [ ]:
array_example.shape

In [13]:
arr_one = np.array ([[1, 2, 3, 4, 5]])

In [14]:
arr_one.ndim

2

# Reshape

In [17]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [19]:
b = a.reshape(3,2)

print (b)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
a.reshape

Convert 1D to 2D

In [20]:
a = np.array ([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [21]:
# you can use np.newaxis to add a new axis:

a2 = a[np.newaxis]
print (a2.shape)
print (a2)

(1, 6)
[[1 2 3 4 5 6]]


In [26]:
# you can convert a 1D array to a row vector by inserting an axis along the first dimension

row_vector = a[np.newaxis, :]
print (row_vector.shape)
print (row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [27]:
# for a column vector, You can insert an axis along the second dimension

col_vector = a[:, np.newaxis]
print (col_vector.shape)
print (col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [28]:
a = np.array ([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [ ]:
# you can use np.expand_dims to add an axis at index

index and slicing

In [32]:
data = np.array([1,2,3])

print (data)
print (data[0])
print (data[1])
print (data[0:2])
print (data[1:])
print (data[-2])

[1 2 3]
1
2
[1 2]
[2 3]
2


In [33]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [35]:
# you can easily print all of the values in the array that are less than 5

print(a[a<5])

[1 2 3 4]


In [37]:
five_up = (a >= 5)

print (a[five_up])
print (a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [38]:
# you can select elements that are divisible by 2 

divisible_by_2 = a[a%2==1]

print(divisible_by_2)

[ 1  3  5  7  9 11]


In [40]:
# you can

c = a[(a > 2) & (a < 11)]
print (c)

[ 3  4  5  6  7  8  9 10]


Creating array from data existing

In [41]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [43]:
arr1 = arr[4:7]
arr1

array([5, 6, 7])

In [48]:
a_1 = np.array ([[1, 1],
               [2, 2]])

In [49]:
a_2 = np.array ([[3, 3],
               [4, 4]])

In [51]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [54]:
 #horizontal with hstack
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [55]:
arrsplit = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                    [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [56]:
# if you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,2)

[array([[ 1,  2,  3,  4,  5,  6],
        [13, 14, 15, 16, 17, 18]]), array([[ 7,  8,  9, 10, 11, 12],
        [19, 20, 21, 22, 23, 24]])]

In [57]:
a = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

In [60]:
# you can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [61]:
c = c.copy()
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

basic array operation

In [62]:
a = np.array([1, 2, 3, 4])

#add all of the elements in the array
a.sum()

10

In [64]:
b = np.array ([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [65]:
data / data

array([1., 1., 1.])

NameError: name 'ones' is not defined

In [71]:
data = np.array([1,2])
data

array([1, 2])

Broadcasting

In [72]:
data * 1.6

array([1.6, 3.2])

In [73]:
data * 2

array([2, 4])

matrix arithmetic

In [74]:
data = np.array ([[1,2], [3,4]])
print (data)

[[1 2]
 [3 4]]


In [75]:
ones = np.ones([2, 2 ])
print(ones)

[[1. 1.]
 [1. 1.]]


In [76]:
print (data + ones)

[[2. 3.]
 [4. 5.]]


In [77]:
ones_row = np.ones ([1, 2])
print(ones_row)

[[1. 1.]]


dot product

In [78]:
a_1 = np.array ([[1, 2, 3, 4], [5, 6, 7, 8],])
print (a_1)

[[1 2 3 4]
 [5 6 7 8]]


In [79]:
a_2 = np.array ([[7, 8], [9, 10], [11, 12]])
print (a_2)

[[ 7  8]
 [ 9 10]
 [11 12]]


matrix indexing


In [83]:
data = np.array ([[1,2], [3,4],[5,6]])

print(data)
print(data[0,1])
print(data[1:3])
print(data[0:2,0])

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]


matrix aggregation

In [84]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [85]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [86]:
print (data.max(axis=0))
print (data.min(axis=1))

[5 6]
[1 3 5]


flatten n-Dimensional array

In [87]:
arrflat = np.array([[1, 2, 3, 4],[5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [88]:
# you can use flatten to flatten your array into a 1D array

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

working with math formulas

notes on numpy vector

In [89]:
a = np.random.rand(5)

In [90]:
print (a)

[0.97561762 0.31901816 0.25376979 0.26835202 0.12828703]


In [91]:
a.shape #rank 1 array

(5,)

In [92]:
print(a.T)

[0.97561762 0.31901816 0.25376979 0.26835202 0.12828703]


In [93]:
print(np.dot(a, a.T))

1.2064718086881


In [94]:
a = np.random.rand(5,1) #column vector

In [96]:
print (a)

[[0.15124429]
 [0.92327386]
 [0.16089977]
 [0.6394379 ]
 [0.11290645]]


In [97]:
print(a.T)

[[0.15124429 0.92327386 0.16089977 0.6394379  0.11290645]]


In [98]:
print(np.random.rand(1,5))

[[0.5764807  0.62540876 0.98625349 0.23789991 0.40602726]]


In [99]:
a = np.array ([[1, 2, 3, 4, 5, 6, 7,]])
print (a)

[[1 2 3 4 5 6 7]]


In [107]:
np.save('h8', a)

In [108]:
b = np.load('h8.npy')

In [102]:
print(b)

[[1 2 3 4 5 6 7]]


In [103]:
arr2D = np.array ([[11, 12, 13, 22],[21, 7, 23,14],[31, 10, 33,7]])

In [104]:
np.savetxt('h8.csv', arr2D)

In [106]:
np.loadtxt('h8.csv')

array([[11., 12., 13., 22.],
       [21.,  7., 23., 14.],
       [31., 10., 33.,  7.]])